/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting.asset.thriftapi
{

  /// <summary>
  /// 子账号资金结算时的资金明细
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SettlementFundDetail : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private long _settlementId;
    private long _subAccountId;
    private double _preFund;
    private string _currency;
    private long _settlementTimestamp;
    private double _depositAmount;
    private double _withdrawAmount;
    private double _closeProfit;
    private double _useMargin;
    private double _useCommission;
    private long _createTimestampMs;
    private long _lastModifyTimestampMs;
    private double _balance;
    private long _exchangeRateHistoryId;
    private double _goodsValue;
    private double _leverage;

    public long SettlementId
    {
      get
      {
        return _settlementId;
      }
      set
      {
        __isset.settlementId = true;
        SetProperty(ref _settlementId, value);
      }
    }

    public long SubAccountId
    {
      get
      {
        return _subAccountId;
      }
      set
      {
        __isset.subAccountId = true;
        SetProperty(ref _subAccountId, value);
      }
    }

    public double PreFund
    {
      get
      {
        return _preFund;
      }
      set
      {
        __isset.preFund = true;
        SetProperty(ref _preFund, value);
      }
    }

    public string Currency
    {
      get
      {
        return _currency;
      }
      set
      {
        __isset.currency = true;
        SetProperty(ref _currency, value);
      }
    }

    public long SettlementTimestamp
    {
      get
      {
        return _settlementTimestamp;
      }
      set
      {
        __isset.settlementTimestamp = true;
        SetProperty(ref _settlementTimestamp, value);
      }
    }

    public double DepositAmount
    {
      get
      {
        return _depositAmount;
      }
      set
      {
        __isset.depositAmount = true;
        SetProperty(ref _depositAmount, value);
      }
    }

    public double WithdrawAmount
    {
      get
      {
        return _withdrawAmount;
      }
      set
      {
        __isset.withdrawAmount = true;
        SetProperty(ref _withdrawAmount, value);
      }
    }

    public double CloseProfit
    {
      get
      {
        return _closeProfit;
      }
      set
      {
        __isset.closeProfit = true;
        SetProperty(ref _closeProfit, value);
      }
    }

    public double UseMargin
    {
      get
      {
        return _useMargin;
      }
      set
      {
        __isset.useMargin = true;
        SetProperty(ref _useMargin, value);
      }
    }

    public double UseCommission
    {
      get
      {
        return _useCommission;
      }
      set
      {
        __isset.useCommission = true;
        SetProperty(ref _useCommission, value);
      }
    }

    public long CreateTimestampMs
    {
      get
      {
        return _createTimestampMs;
      }
      set
      {
        __isset.createTimestampMs = true;
        SetProperty(ref _createTimestampMs, value);
      }
    }

    public long LastModifyTimestampMs
    {
      get
      {
        return _lastModifyTimestampMs;
      }
      set
      {
        __isset.lastModifyTimestampMs = true;
        SetProperty(ref _lastModifyTimestampMs, value);
      }
    }

    public double Balance
    {
      get
      {
        return _balance;
      }
      set
      {
        __isset.balance = true;
        SetProperty(ref _balance, value);
      }
    }

    public long ExchangeRateHistoryId
    {
      get
      {
        return _exchangeRateHistoryId;
      }
      set
      {
        __isset.exchangeRateHistoryId = true;
        SetProperty(ref _exchangeRateHistoryId, value);
      }
    }

    public double GoodsValue
    {
      get
      {
        return _goodsValue;
      }
      set
      {
        __isset.goodsValue = true;
        SetProperty(ref _goodsValue, value);
      }
    }

    public double Leverage
    {
      get
      {
        return _leverage;
      }
      set
      {
        __isset.leverage = true;
        SetProperty(ref _leverage, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool settlementId;
      public bool subAccountId;
      public bool preFund;
      public bool currency;
      public bool settlementTimestamp;
      public bool depositAmount;
      public bool withdrawAmount;
      public bool closeProfit;
      public bool useMargin;
      public bool useCommission;
      public bool createTimestampMs;
      public bool lastModifyTimestampMs;
      public bool balance;
      public bool exchangeRateHistoryId;
      public bool goodsValue;
      public bool leverage;
    }

    public SettlementFundDetail() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              SettlementId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              SubAccountId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Double) {
              PreFund = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Currency = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I64) {
              SettlementTimestamp = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.Double) {
              DepositAmount = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.Double) {
              WithdrawAmount = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.Double) {
              CloseProfit = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.Double) {
              UseMargin = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.Double) {
              UseCommission = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.I64) {
              CreateTimestampMs = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.I64) {
              LastModifyTimestampMs = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 13:
            if (field.Type == TType.Double) {
              Balance = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 14:
            if (field.Type == TType.I64) {
              ExchangeRateHistoryId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 16:
            if (field.Type == TType.Double) {
              GoodsValue = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 17:
            if (field.Type == TType.Double) {
              Leverage = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SettlementFundDetail");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.settlementId) {
        field.Name = "settlementId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SettlementId);
        oprot.WriteFieldEnd();
      }
      if (__isset.subAccountId) {
        field.Name = "subAccountId";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SubAccountId);
        oprot.WriteFieldEnd();
      }
      if (__isset.preFund) {
        field.Name = "preFund";
        field.Type = TType.Double;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(PreFund);
        oprot.WriteFieldEnd();
      }
      if (Currency != null && __isset.currency) {
        field.Name = "currency";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Currency);
        oprot.WriteFieldEnd();
      }
      if (__isset.settlementTimestamp) {
        field.Name = "settlementTimestamp";
        field.Type = TType.I64;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SettlementTimestamp);
        oprot.WriteFieldEnd();
      }
      if (__isset.depositAmount) {
        field.Name = "depositAmount";
        field.Type = TType.Double;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(DepositAmount);
        oprot.WriteFieldEnd();
      }
      if (__isset.withdrawAmount) {
        field.Name = "withdrawAmount";
        field.Type = TType.Double;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(WithdrawAmount);
        oprot.WriteFieldEnd();
      }
      if (__isset.closeProfit) {
        field.Name = "closeProfit";
        field.Type = TType.Double;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(CloseProfit);
        oprot.WriteFieldEnd();
      }
      if (__isset.useMargin) {
        field.Name = "useMargin";
        field.Type = TType.Double;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(UseMargin);
        oprot.WriteFieldEnd();
      }
      if (__isset.useCommission) {
        field.Name = "useCommission";
        field.Type = TType.Double;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(UseCommission);
        oprot.WriteFieldEnd();
      }
      if (__isset.createTimestampMs) {
        field.Name = "createTimestampMs";
        field.Type = TType.I64;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(CreateTimestampMs);
        oprot.WriteFieldEnd();
      }
      if (__isset.lastModifyTimestampMs) {
        field.Name = "lastModifyTimestampMs";
        field.Type = TType.I64;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(LastModifyTimestampMs);
        oprot.WriteFieldEnd();
      }
      if (__isset.balance) {
        field.Name = "balance";
        field.Type = TType.Double;
        field.ID = 13;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Balance);
        oprot.WriteFieldEnd();
      }
      if (__isset.exchangeRateHistoryId) {
        field.Name = "exchangeRateHistoryId";
        field.Type = TType.I64;
        field.ID = 14;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(ExchangeRateHistoryId);
        oprot.WriteFieldEnd();
      }
      if (__isset.goodsValue) {
        field.Name = "goodsValue";
        field.Type = TType.Double;
        field.ID = 16;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(GoodsValue);
        oprot.WriteFieldEnd();
      }
      if (__isset.leverage) {
        field.Name = "leverage";
        field.Type = TType.Double;
        field.ID = 17;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Leverage);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SettlementFundDetail(");
      sb.Append("SettlementId: ");
      sb.Append(SettlementId);
      sb.Append(",SubAccountId: ");
      sb.Append(SubAccountId);
      sb.Append(",PreFund: ");
      sb.Append(PreFund);
      sb.Append(",Currency: ");
      sb.Append(Currency);
      sb.Append(",SettlementTimestamp: ");
      sb.Append(SettlementTimestamp);
      sb.Append(",DepositAmount: ");
      sb.Append(DepositAmount);
      sb.Append(",WithdrawAmount: ");
      sb.Append(WithdrawAmount);
      sb.Append(",CloseProfit: ");
      sb.Append(CloseProfit);
      sb.Append(",UseMargin: ");
      sb.Append(UseMargin);
      sb.Append(",UseCommission: ");
      sb.Append(UseCommission);
      sb.Append(",CreateTimestampMs: ");
      sb.Append(CreateTimestampMs);
      sb.Append(",LastModifyTimestampMs: ");
      sb.Append(LastModifyTimestampMs);
      sb.Append(",Balance: ");
      sb.Append(Balance);
      sb.Append(",ExchangeRateHistoryId: ");
      sb.Append(ExchangeRateHistoryId);
      sb.Append(",GoodsValue: ");
      sb.Append(GoodsValue);
      sb.Append(",Leverage: ");
      sb.Append(Leverage);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
