/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting.asset.thriftapi
{

  /// <summary>
  /// 子账号合约持仓结算明细
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SettlementPositionDetail : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private long _settlementId;
    private long _sledContractId;
    private long _subAccountId;
    private long _position;
    private double _positionAvgPrice;
    private double _positionProfit;
    private double _calculatePrice;
    private string _currency;
    private long _sledCommodityId;
    private long _prevPosition;
    private long _longPosition;
    private long _shortPosition;
    private double _closeProfit;
    private double _goodsValue;
    private double _leverage;
    private double _useMargin;
    private double _useCommission;
    private long _createTimestampMs;
    private long _lastmodifyTimestampMs;

    public long SettlementId
    {
      get
      {
        return _settlementId;
      }
      set
      {
        __isset.settlementId = true;
        SetProperty(ref _settlementId, value);
      }
    }

    public long SledContractId
    {
      get
      {
        return _sledContractId;
      }
      set
      {
        __isset.sledContractId = true;
        SetProperty(ref _sledContractId, value);
      }
    }

    public long SubAccountId
    {
      get
      {
        return _subAccountId;
      }
      set
      {
        __isset.subAccountId = true;
        SetProperty(ref _subAccountId, value);
      }
    }

    public long Position
    {
      get
      {
        return _position;
      }
      set
      {
        __isset.position = true;
        SetProperty(ref _position, value);
      }
    }

    public double PositionAvgPrice
    {
      get
      {
        return _positionAvgPrice;
      }
      set
      {
        __isset.positionAvgPrice = true;
        SetProperty(ref _positionAvgPrice, value);
      }
    }

    public double PositionProfit
    {
      get
      {
        return _positionProfit;
      }
      set
      {
        __isset.positionProfit = true;
        SetProperty(ref _positionProfit, value);
      }
    }

    public double CalculatePrice
    {
      get
      {
        return _calculatePrice;
      }
      set
      {
        __isset.calculatePrice = true;
        SetProperty(ref _calculatePrice, value);
      }
    }

    public string Currency
    {
      get
      {
        return _currency;
      }
      set
      {
        __isset.currency = true;
        SetProperty(ref _currency, value);
      }
    }

    public long SledCommodityId
    {
      get
      {
        return _sledCommodityId;
      }
      set
      {
        __isset.sledCommodityId = true;
        SetProperty(ref _sledCommodityId, value);
      }
    }

    public long PrevPosition
    {
      get
      {
        return _prevPosition;
      }
      set
      {
        __isset.prevPosition = true;
        SetProperty(ref _prevPosition, value);
      }
    }

    public long LongPosition
    {
      get
      {
        return _longPosition;
      }
      set
      {
        __isset.longPosition = true;
        SetProperty(ref _longPosition, value);
      }
    }

    public long ShortPosition
    {
      get
      {
        return _shortPosition;
      }
      set
      {
        __isset.shortPosition = true;
        SetProperty(ref _shortPosition, value);
      }
    }

    public double CloseProfit
    {
      get
      {
        return _closeProfit;
      }
      set
      {
        __isset.closeProfit = true;
        SetProperty(ref _closeProfit, value);
      }
    }

    public double GoodsValue
    {
      get
      {
        return _goodsValue;
      }
      set
      {
        __isset.goodsValue = true;
        SetProperty(ref _goodsValue, value);
      }
    }

    public double Leverage
    {
      get
      {
        return _leverage;
      }
      set
      {
        __isset.leverage = true;
        SetProperty(ref _leverage, value);
      }
    }

    public double UseMargin
    {
      get
      {
        return _useMargin;
      }
      set
      {
        __isset.useMargin = true;
        SetProperty(ref _useMargin, value);
      }
    }

    public double UseCommission
    {
      get
      {
        return _useCommission;
      }
      set
      {
        __isset.useCommission = true;
        SetProperty(ref _useCommission, value);
      }
    }

    public long CreateTimestampMs
    {
      get
      {
        return _createTimestampMs;
      }
      set
      {
        __isset.createTimestampMs = true;
        SetProperty(ref _createTimestampMs, value);
      }
    }

    public long LastmodifyTimestampMs
    {
      get
      {
        return _lastmodifyTimestampMs;
      }
      set
      {
        __isset.lastmodifyTimestampMs = true;
        SetProperty(ref _lastmodifyTimestampMs, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool settlementId;
      public bool sledContractId;
      public bool subAccountId;
      public bool position;
      public bool positionAvgPrice;
      public bool positionProfit;
      public bool calculatePrice;
      public bool currency;
      public bool sledCommodityId;
      public bool prevPosition;
      public bool longPosition;
      public bool shortPosition;
      public bool closeProfit;
      public bool goodsValue;
      public bool leverage;
      public bool useMargin;
      public bool useCommission;
      public bool createTimestampMs;
      public bool lastmodifyTimestampMs;
    }

    public SettlementPositionDetail() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              SettlementId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              SledContractId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              SubAccountId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I64) {
              Position = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Double) {
              PositionAvgPrice = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.Double) {
              PositionProfit = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.Double) {
              CalculatePrice = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.String) {
              Currency = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.I64) {
              SledCommodityId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.I64) {
              PrevPosition = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 13:
            if (field.Type == TType.I64) {
              LongPosition = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 14:
            if (field.Type == TType.I64) {
              ShortPosition = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 15:
            if (field.Type == TType.Double) {
              CloseProfit = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 16:
            if (field.Type == TType.Double) {
              GoodsValue = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 17:
            if (field.Type == TType.Double) {
              Leverage = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 18:
            if (field.Type == TType.Double) {
              UseMargin = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 19:
            if (field.Type == TType.Double) {
              UseCommission = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.I64) {
              CreateTimestampMs = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 31:
            if (field.Type == TType.I64) {
              LastmodifyTimestampMs = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SettlementPositionDetail");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.settlementId) {
        field.Name = "settlementId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SettlementId);
        oprot.WriteFieldEnd();
      }
      if (__isset.sledContractId) {
        field.Name = "sledContractId";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SledContractId);
        oprot.WriteFieldEnd();
      }
      if (__isset.subAccountId) {
        field.Name = "subAccountId";
        field.Type = TType.I64;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SubAccountId);
        oprot.WriteFieldEnd();
      }
      if (__isset.position) {
        field.Name = "position";
        field.Type = TType.I64;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Position);
        oprot.WriteFieldEnd();
      }
      if (__isset.positionAvgPrice) {
        field.Name = "positionAvgPrice";
        field.Type = TType.Double;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(PositionAvgPrice);
        oprot.WriteFieldEnd();
      }
      if (__isset.positionProfit) {
        field.Name = "positionProfit";
        field.Type = TType.Double;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(PositionProfit);
        oprot.WriteFieldEnd();
      }
      if (__isset.calculatePrice) {
        field.Name = "calculatePrice";
        field.Type = TType.Double;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(CalculatePrice);
        oprot.WriteFieldEnd();
      }
      if (Currency != null && __isset.currency) {
        field.Name = "currency";
        field.Type = TType.String;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Currency);
        oprot.WriteFieldEnd();
      }
      if (__isset.sledCommodityId) {
        field.Name = "sledCommodityId";
        field.Type = TType.I64;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(SledCommodityId);
        oprot.WriteFieldEnd();
      }
      if (__isset.prevPosition) {
        field.Name = "prevPosition";
        field.Type = TType.I64;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(PrevPosition);
        oprot.WriteFieldEnd();
      }
      if (__isset.longPosition) {
        field.Name = "longPosition";
        field.Type = TType.I64;
        field.ID = 13;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(LongPosition);
        oprot.WriteFieldEnd();
      }
      if (__isset.shortPosition) {
        field.Name = "shortPosition";
        field.Type = TType.I64;
        field.ID = 14;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(ShortPosition);
        oprot.WriteFieldEnd();
      }
      if (__isset.closeProfit) {
        field.Name = "closeProfit";
        field.Type = TType.Double;
        field.ID = 15;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(CloseProfit);
        oprot.WriteFieldEnd();
      }
      if (__isset.goodsValue) {
        field.Name = "goodsValue";
        field.Type = TType.Double;
        field.ID = 16;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(GoodsValue);
        oprot.WriteFieldEnd();
      }
      if (__isset.leverage) {
        field.Name = "leverage";
        field.Type = TType.Double;
        field.ID = 17;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(Leverage);
        oprot.WriteFieldEnd();
      }
      if (__isset.useMargin) {
        field.Name = "useMargin";
        field.Type = TType.Double;
        field.ID = 18;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(UseMargin);
        oprot.WriteFieldEnd();
      }
      if (__isset.useCommission) {
        field.Name = "useCommission";
        field.Type = TType.Double;
        field.ID = 19;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(UseCommission);
        oprot.WriteFieldEnd();
      }
      if (__isset.createTimestampMs) {
        field.Name = "createTimestampMs";
        field.Type = TType.I64;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(CreateTimestampMs);
        oprot.WriteFieldEnd();
      }
      if (__isset.lastmodifyTimestampMs) {
        field.Name = "lastmodifyTimestampMs";
        field.Type = TType.I64;
        field.ID = 31;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(LastmodifyTimestampMs);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SettlementPositionDetail(");
      sb.Append("SettlementId: ");
      sb.Append(SettlementId);
      sb.Append(",SledContractId: ");
      sb.Append(SledContractId);
      sb.Append(",SubAccountId: ");
      sb.Append(SubAccountId);
      sb.Append(",Position: ");
      sb.Append(Position);
      sb.Append(",PositionAvgPrice: ");
      sb.Append(PositionAvgPrice);
      sb.Append(",PositionProfit: ");
      sb.Append(PositionProfit);
      sb.Append(",CalculatePrice: ");
      sb.Append(CalculatePrice);
      sb.Append(",Currency: ");
      sb.Append(Currency);
      sb.Append(",SledCommodityId: ");
      sb.Append(SledCommodityId);
      sb.Append(",PrevPosition: ");
      sb.Append(PrevPosition);
      sb.Append(",LongPosition: ");
      sb.Append(LongPosition);
      sb.Append(",ShortPosition: ");
      sb.Append(ShortPosition);
      sb.Append(",CloseProfit: ");
      sb.Append(CloseProfit);
      sb.Append(",GoodsValue: ");
      sb.Append(GoodsValue);
      sb.Append(",Leverage: ");
      sb.Append(Leverage);
      sb.Append(",UseMargin: ");
      sb.Append(UseMargin);
      sb.Append(",UseCommission: ");
      sb.Append(UseCommission);
      sb.Append(",CreateTimestampMs: ");
      sb.Append(CreateTimestampMs);
      sb.Append(",LastmodifyTimestampMs: ");
      sb.Append(LastmodifyTimestampMs);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
