/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.trade.hosting.arbitrage.thriftapi
{
  public enum HostingXQOrderStateValue
  {
    XQ_ORDER_CREATED = 1,
    XQ_ORDER_CANCELLED = 2,
    XQ_ORDER_CANCELLING = 3,
    XQ_ORDER_SUSPENDED = 4,
    XQ_ORDER_SUSPENDING = 5,
    XQ_ORDER_RUNNING = 6,
    XQ_ORDER_STARTING = 7,
    XQ_ORDER_FINISHED = 8,
    XQ_ORDER_FINISHING = 9,
  }
}
