/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.trade.hosting.arbitrage.thriftapi
{
  public enum HostingXQEffectDateType
  {
    XQ_EFFECT_TODAY = 1,
    XQ_EFFECT_PERIOD = 2,
    XQ_EFFECT_FOREVER = 3,
  }
}
