/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.contract.standard
{
  public enum ContractStatus
  {
    NORMAL = 0,
    EXPIRED = 1,
    DISABLED = 2,
  }
}
