/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.trade.hosting.tasknote.thriftapi
{
  public enum HostingTaskNoteType
  {
    XQ_TRADE_LAME = 1,
  }
}
