/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting.position.statis
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class StatPositionSummaryPage : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private int _totalNum;
    private List<StatPositionSummary> _statPositionSummaryList;

    public int TotalNum
    {
      get
      {
        return _totalNum;
      }
      set
      {
        __isset.totalNum = true;
        SetProperty(ref _totalNum, value);
      }
    }

    public List<StatPositionSummary> StatPositionSummaryList
    {
      get
      {
        return _statPositionSummaryList;
      }
      set
      {
        __isset.statPositionSummaryList = true;
        SetProperty(ref _statPositionSummaryList, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool totalNum;
      public bool statPositionSummaryList;
    }

    public StatPositionSummaryPage() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              TotalNum = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                StatPositionSummaryList = new List<StatPositionSummary>();
                TList _list36 = iprot.ReadListBegin();
                for( int _i37 = 0; _i37 < _list36.Count; ++_i37)
                {
                  StatPositionSummary _elem38 = new StatPositionSummary();
                  _elem38 = new StatPositionSummary();
                  _elem38.Read(iprot);
                  StatPositionSummaryList.Add(_elem38);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("StatPositionSummaryPage");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.totalNum) {
        field.Name = "totalNum";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TotalNum);
        oprot.WriteFieldEnd();
      }
      if (StatPositionSummaryList != null && __isset.statPositionSummaryList) {
        field.Name = "statPositionSummaryList";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, StatPositionSummaryList.Count));
          foreach (StatPositionSummary _iter39 in StatPositionSummaryList)
          {
            _iter39.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("StatPositionSummaryPage(");
      sb.Append("TotalNum: ");
      sb.Append(TotalNum);
      sb.Append(",StatPositionSummaryList: ");
      if (StatPositionSummaryList == null)
      {
        sb.Append("<null>");
      }
      else
      {
        sb.Append("[");
        foreach (StatPositionSummary _iter40 in StatPositionSummaryList)
        {
          sb.Append(_iter40.ToString());
          sb.Append(", ");
        }
        sb.Append("]");
      }
      sb.Append(")");
      return sb.ToString();
    }

  }

}
