/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting.position.statis
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class StatClosedPositionDetail : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private int _totalNum;
    private List<StatClosedPositionItem> _statClosedPositionItemList;

    public int TotalNum
    {
      get
      {
        return _totalNum;
      }
      set
      {
        __isset.totalNum = true;
        SetProperty(ref _totalNum, value);
      }
    }

    public List<StatClosedPositionItem> StatClosedPositionItemList
    {
      get
      {
        return _statClosedPositionItemList;
      }
      set
      {
        __isset.statClosedPositionItemList = true;
        SetProperty(ref _statClosedPositionItemList, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool totalNum;
      public bool statClosedPositionItemList;
    }

    public StatClosedPositionDetail() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              TotalNum = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                StatClosedPositionItemList = new List<StatClosedPositionItem>();
                TList _list56 = iprot.ReadListBegin();
                for( int _i57 = 0; _i57 < _list56.Count; ++_i57)
                {
                  StatClosedPositionItem _elem58 = new StatClosedPositionItem();
                  _elem58 = new StatClosedPositionItem();
                  _elem58.Read(iprot);
                  StatClosedPositionItemList.Add(_elem58);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("StatClosedPositionDetail");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.totalNum) {
        field.Name = "totalNum";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TotalNum);
        oprot.WriteFieldEnd();
      }
      if (StatClosedPositionItemList != null && __isset.statClosedPositionItemList) {
        field.Name = "statClosedPositionItemList";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, StatClosedPositionItemList.Count));
          foreach (StatClosedPositionItem _iter59 in StatClosedPositionItemList)
          {
            _iter59.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("StatClosedPositionDetail(");
      sb.Append("TotalNum: ");
      sb.Append(TotalNum);
      sb.Append(",StatClosedPositionItemList: ");
      if (StatClosedPositionItemList == null)
      {
        sb.Append("<null>");
      }
      else
      {
        sb.Append("[");
        foreach (StatClosedPositionItem _iter60 in StatClosedPositionItemList)
        {
          sb.Append(_iter60.ToString());
          sb.Append(", ");
        }
        sb.Append("]");
      }
      sb.Append(")");
      return sb.ToString();
    }

  }

}
