/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.trade.hosting.position.statis
{
  public enum StatDirection
  {
    STAT_BUY = 0,
    STAT_SELL = 1,
  }
}
