/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.contract
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SledTradingSession : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private long _tradeSessionId;
    private int _sledCommodityId;
    private string _zoneId;
    private List<SledTradingSessionTimeSpan> _timeSpans;
    private TimeSystem _timeSystem;
    private long _createTimestamp;
    private long _lastModifyTimestamp;

    public long TradeSessionId
    {
      get
      {
        return _tradeSessionId;
      }
      set
      {
        __isset.tradeSessionId = true;
        SetProperty(ref _tradeSessionId, value);
      }
    }

    public int SledCommodityId
    {
      get
      {
        return _sledCommodityId;
      }
      set
      {
        __isset.sledCommodityId = true;
        SetProperty(ref _sledCommodityId, value);
      }
    }

    public string ZoneId
    {
      get
      {
        return _zoneId;
      }
      set
      {
        __isset.zoneId = true;
        SetProperty(ref _zoneId, value);
      }
    }

    public List<SledTradingSessionTimeSpan> TimeSpans
    {
      get
      {
        return _timeSpans;
      }
      set
      {
        __isset.timeSpans = true;
        SetProperty(ref _timeSpans, value);
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="TimeSystem"/>
    /// </summary>
    public TimeSystem TimeSystem
    {
      get
      {
        return _timeSystem;
      }
      set
      {
        __isset.timeSystem = true;
        SetProperty(ref _timeSystem, value);
      }
    }

    public long CreateTimestamp
    {
      get
      {
        return _createTimestamp;
      }
      set
      {
        __isset.createTimestamp = true;
        SetProperty(ref _createTimestamp, value);
      }
    }

    public long LastModifyTimestamp
    {
      get
      {
        return _lastModifyTimestamp;
      }
      set
      {
        __isset.lastModifyTimestamp = true;
        SetProperty(ref _lastModifyTimestamp, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool tradeSessionId;
      public bool sledCommodityId;
      public bool zoneId;
      public bool timeSpans;
      public bool timeSystem;
      public bool createTimestamp;
      public bool lastModifyTimestamp;
    }

    public SledTradingSession() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              TradeSessionId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              SledCommodityId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              ZoneId = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                TimeSpans = new List<SledTradingSessionTimeSpan>();
                TList _list85 = iprot.ReadListBegin();
                for( int _i86 = 0; _i86 < _list85.Count; ++_i86)
                {
                  SledTradingSessionTimeSpan _elem87 = new SledTradingSessionTimeSpan();
                  _elem87 = new SledTradingSessionTimeSpan();
                  _elem87.Read(iprot);
                  TimeSpans.Add(_elem87);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              TimeSystem = (TimeSystem)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.I64) {
              CreateTimestamp = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I64) {
              LastModifyTimestamp = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SledTradingSession");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.tradeSessionId) {
        field.Name = "tradeSessionId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(TradeSessionId);
        oprot.WriteFieldEnd();
      }
      if (__isset.sledCommodityId) {
        field.Name = "sledCommodityId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SledCommodityId);
        oprot.WriteFieldEnd();
      }
      if (ZoneId != null && __isset.zoneId) {
        field.Name = "zoneId";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ZoneId);
        oprot.WriteFieldEnd();
      }
      if (TimeSpans != null && __isset.timeSpans) {
        field.Name = "timeSpans";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, TimeSpans.Count));
          foreach (SledTradingSessionTimeSpan _iter88 in TimeSpans)
          {
            _iter88.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.timeSystem) {
        field.Name = "timeSystem";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)TimeSystem);
        oprot.WriteFieldEnd();
      }
      if (__isset.createTimestamp) {
        field.Name = "createTimestamp";
        field.Type = TType.I64;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(CreateTimestamp);
        oprot.WriteFieldEnd();
      }
      if (__isset.lastModifyTimestamp) {
        field.Name = "lastModifyTimestamp";
        field.Type = TType.I64;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(LastModifyTimestamp);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SledTradingSession(");
      sb.Append("TradeSessionId: ");
      sb.Append(TradeSessionId);
      sb.Append(",SledCommodityId: ");
      sb.Append(SledCommodityId);
      sb.Append(",ZoneId: ");
      sb.Append(ZoneId);
      sb.Append(",TimeSpans: ");
      if (TimeSpans == null)
      {
        sb.Append("<null>");
      }
      else
      {
        sb.Append("[");
        foreach (SledTradingSessionTimeSpan _iter89 in TimeSpans)
        {
          sb.Append(_iter89.ToString());
          sb.Append(", ");
        }
        sb.Append("]");
      }
      sb.Append(",TimeSystem: ");
      sb.Append(TimeSystem);
      sb.Append(",CreateTimestamp: ");
      sb.Append(CreateTimestamp);
      sb.Append(",LastModifyTimestamp: ");
      sb.Append(LastModifyTimestamp);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
