/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 

namespace xueqiao.trade.hosting.risk.manager.thriftapi
{
  public static class trade_hosting_risk_managerConstants
  {
    public static string PARAM_RISKITEM_COMMODITY_ID = "cmId";
    public static string PARAM_RISKITEM_CONTRACT_ID = "cnId";
  }
}
