/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CTPOrderRef : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private int _frontID;
    private int _sessionID;
    private string _orderRef;

    public int FrontID
    {
      get
      {
        return _frontID;
      }
      set
      {
        __isset.frontID = true;
        SetProperty(ref _frontID, value);
      }
    }

    public int SessionID
    {
      get
      {
        return _sessionID;
      }
      set
      {
        __isset.sessionID = true;
        SetProperty(ref _sessionID, value);
      }
    }

    public string OrderRef
    {
      get
      {
        return _orderRef;
      }
      set
      {
        __isset.orderRef = true;
        SetProperty(ref _orderRef, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool frontID;
      public bool sessionID;
      public bool orderRef;
    }

    public CTPOrderRef() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              FrontID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              SessionID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              OrderRef = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CTPOrderRef");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.frontID) {
        field.Name = "frontID";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(FrontID);
        oprot.WriteFieldEnd();
      }
      if (__isset.sessionID) {
        field.Name = "sessionID";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SessionID);
        oprot.WriteFieldEnd();
      }
      if (OrderRef != null && __isset.orderRef) {
        field.Name = "orderRef";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(OrderRef);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CTPOrderRef(");
      sb.Append("FrontID: ");
      sb.Append(FrontID);
      sb.Append(",SessionID: ");
      sb.Append(SessionID);
      sb.Append(",OrderRef: ");
      sb.Append(OrderRef);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
