/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.trade.hosting
{
  public enum HostingComposeViewSource
  {
    USER_CREATED = 1,
    USER_SEARCHED = 2,
    GRAPH_SHARED = 3,
  }
}
