/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.trade.hosting
{
  public enum HostingUserOrderType
  {
    OrderByCreateTimestampAsc = 1,
    OrderByCreateTimestampDesc = 2,
    OrderByLoginNameAsc = 3,
    OrderByLoginNameDesc = 4,
  }
}
