/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class HostingOrderRouteTree : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private int _configVersion;
    private Dictionary<string, HostingOrderRouteExchangeNode> _subExchangeNodes;

    public int ConfigVersion
    {
      get
      {
        return _configVersion;
      }
      set
      {
        __isset.configVersion = true;
        SetProperty(ref _configVersion, value);
      }
    }

    public Dictionary<string, HostingOrderRouteExchangeNode> SubExchangeNodes
    {
      get
      {
        return _subExchangeNodes;
      }
      set
      {
        __isset.subExchangeNodes = true;
        SetProperty(ref _subExchangeNodes, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool configVersion;
      public bool subExchangeNodes;
    }

    public HostingOrderRouteTree() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ConfigVersion = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                SubExchangeNodes = new Dictionary<string, HostingOrderRouteExchangeNode>();
                TMap _map29 = iprot.ReadMapBegin();
                for( int _i30 = 0; _i30 < _map29.Count; ++_i30)
                {
                  string _key31;
                  HostingOrderRouteExchangeNode _val32;
                  _key31 = iprot.ReadString();
                  _val32 = new HostingOrderRouteExchangeNode();
                  _val32.Read(iprot);
                  SubExchangeNodes[_key31] = _val32;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("HostingOrderRouteTree");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.configVersion) {
        field.Name = "configVersion";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ConfigVersion);
        oprot.WriteFieldEnd();
      }
      if (SubExchangeNodes != null && __isset.subExchangeNodes) {
        field.Name = "subExchangeNodes";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.Struct, SubExchangeNodes.Count));
          foreach (string _iter33 in SubExchangeNodes.Keys)
          {
            oprot.WriteString(_iter33);
            SubExchangeNodes[_iter33].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("HostingOrderRouteTree(");
      sb.Append("ConfigVersion: ");
      sb.Append(ConfigVersion);
      sb.Append(",SubExchangeNodes: ");
      if (SubExchangeNodes == null)
      {
        sb.Append("<null>");
      }
      else
      {
        sb.Append("{");
        foreach (string _iter34 in SubExchangeNodes.Keys)
        {
          sb.Append(_iter34.ToString());
          sb.Append(":");
          sb.Append(SubExchangeNodes[_iter34].ToString());
          sb.Append(", ");
        }
        sb.Append("}");
      }
      sb.Append(")");
      return sb.ToString();
    }

  }

}
