/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.trade.hosting.position.fee.thriftapi
{
  public enum UpsideDataType
  {
    UDT_NO_DATA = 0,
    UDT_COMMODITY = 1,
    UDT_CONTRACT = 2,
  }
}
