/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace xueqiao.graph.xiaoha.chart.thriftapi
{
  /// <summary>
  /// 图表类型
  /// </summary>
  public enum ChartType
  {
    HISTORICAL_DATA = 0,
    SPREAD_MONTH = 1,
    SPREAD_COMMODITY = 2,
    FORWARD_CURVE = 3,
  }
}
