/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 

namespace xueqiao.quotation
{
  public static class quotation_itemConstants
  {
    public static string PLATFORM_CTP = "CTP";
    public static string PLATFORM_SIMU_CTP = "SCTP";
    public static string PLATFORM_SP = "SP";
    public static string PLATFORM_SIMU_SP = "ESP";
    public static string PLATFORM_ESUNNY = "ES";
    public static string PLATFROM_SIMY_ESUNNY = "SES";
    public static string PLATFORM_XUEQIAO = "XQ";
    public static string PLATFORM_SIMU_XUEQIAO = "SXQ";
  }
}
