/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting.proxy
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ProxyFakeLoginResp : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private List<ProxyCompanyGroup> _companyGroups;
    private string _companyCode;

    public List<ProxyCompanyGroup> CompanyGroups
    {
      get
      {
        return _companyGroups;
      }
      set
      {
        __isset.companyGroups = true;
        SetProperty(ref _companyGroups, value);
      }
    }

    public string CompanyCode
    {
      get
      {
        return _companyCode;
      }
      set
      {
        __isset.companyCode = true;
        SetProperty(ref _companyCode, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool companyGroups;
      public bool companyCode;
    }

    public ProxyFakeLoginResp() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                CompanyGroups = new List<ProxyCompanyGroup>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  ProxyCompanyGroup _elem2 = new ProxyCompanyGroup();
                  _elem2 = new ProxyCompanyGroup();
                  _elem2.Read(iprot);
                  CompanyGroups.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              CompanyCode = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ProxyFakeLoginResp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (CompanyGroups != null && __isset.companyGroups) {
        field.Name = "companyGroups";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, CompanyGroups.Count));
          foreach (ProxyCompanyGroup _iter3 in CompanyGroups)
          {
            _iter3.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (CompanyCode != null && __isset.companyCode) {
        field.Name = "companyCode";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(CompanyCode);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ProxyFakeLoginResp(");
      sb.Append("CompanyGroups: ");
      if (CompanyGroups == null)
      {
        sb.Append("<null>");
      }
      else
      {
        sb.Append("[");
        foreach (ProxyCompanyGroup _iter4 in CompanyGroups)
        {
          sb.Append(_iter4.ToString());
          sb.Append(", ");
        }
        sb.Append("]");
      }
      sb.Append(",CompanyCode: ");
      sb.Append(CompanyCode);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
