/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting.proxy
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UpdateInfoReq : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private long _companyId;
    private string _appKey;
    private VersionNum _versionNum;
    private string _companyCode;

    public long CompanyId
    {
      get
      {
        return _companyId;
      }
      set
      {
        __isset.companyId = true;
        SetProperty(ref _companyId, value);
      }
    }

    public string AppKey
    {
      get
      {
        return _appKey;
      }
      set
      {
        __isset.appKey = true;
        SetProperty(ref _appKey, value);
      }
    }

    public VersionNum VersionNum
    {
      get
      {
        return _versionNum;
      }
      set
      {
        __isset.versionNum = true;
        SetProperty(ref _versionNum, value);
      }
    }

    public string CompanyCode
    {
      get
      {
        return _companyCode;
      }
      set
      {
        __isset.companyCode = true;
        SetProperty(ref _companyCode, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool companyId;
      public bool appKey;
      public bool versionNum;
      public bool companyCode;
    }

    public UpdateInfoReq() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              CompanyId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              AppKey = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              VersionNum = new VersionNum();
              VersionNum.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              CompanyCode = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("UpdateInfoReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.companyId) {
        field.Name = "companyId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(CompanyId);
        oprot.WriteFieldEnd();
      }
      if (AppKey != null && __isset.appKey) {
        field.Name = "appKey";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(AppKey);
        oprot.WriteFieldEnd();
      }
      if (VersionNum != null && __isset.versionNum) {
        field.Name = "versionNum";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        VersionNum.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (CompanyCode != null && __isset.companyCode) {
        field.Name = "companyCode";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(CompanyCode);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("UpdateInfoReq(");
      sb.Append("CompanyId: ");
      sb.Append(CompanyId);
      sb.Append(",AppKey: ");
      sb.Append(AppKey);
      sb.Append(",VersionNum: ");
      sb.Append(VersionNum== null ? "<null>" : VersionNum.ToString());
      sb.Append(",CompanyCode: ");
      sb.Append(CompanyCode);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
