/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices; 
using Thrift.Protocol;
using Thrift.Transport;

namespace xueqiao.trade.hosting.events
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class XQOrderChangedEvent : TBase, INotifyPropertyChanged
  {
    public event PropertyChangedEventHandler PropertyChanged;
    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
      if (Equals(field, value)) { return false; }
      field = value;
      RaisePropertyChanged(propertyName);
      return true;
    }

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
    private xueqiao.trade.hosting.arbitrage.thriftapi.HostingXQOrder _changedOrder;

    public xueqiao.trade.hosting.arbitrage.thriftapi.HostingXQOrder ChangedOrder
    {
      get
      {
        return _changedOrder;
      }
      set
      {
        __isset.changedOrder = true;
        SetProperty(ref _changedOrder, value);
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool changedOrder;
    }

    public XQOrderChangedEvent() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              ChangedOrder = new xueqiao.trade.hosting.arbitrage.thriftapi.HostingXQOrder();
              ChangedOrder.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("XQOrderChangedEvent");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ChangedOrder != null && __isset.changedOrder) {
        field.Name = "changedOrder";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        ChangedOrder.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("XQOrderChangedEvent(");
      sb.Append("ChangedOrder: ");
      sb.Append(ChangedOrder== null ? "<null>" : ChangedOrder.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
